---
R1:

  hostname: 192.168.122.101

  groups:

    - IOS_Routers
R2:

  hostname: 192.168.122.102

  groups:

    - IOS_Routers
R3:

  hostname: 192.168.122.103

  groups:

    - IOS_Routers
R4:

  hostname: 192.168.122.104

  groups:

    - IOS_Routers
R5:

  hostname: 192.168.122.105

  groups:

    - IOS_Routers
